### ISSUE TITLE
Test VM w/ Ubuntu 20.04

### ISSUE THREAD

**Issue by phoward38** [Tychobra/shiny_scripts#1]
- [ ] Deploy app to VM w/ Ubuntu 20.04 LTS
  - Reference: https://github.com/rstudio/shiny/issues/3041

**Comment by phoward38** [comment]
**UPDATE:** 
- Note shown on VM SSH start:
```
New release '20.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.
```

- [ ] Create VM w/ Ubuntu 18.04.4 LTS
  - [ ] Deploy app
    - [ ] Include `CRON` job, `sshpass`, & other system objects that could potentially be affected
- [ ] Test `do-release-upgrade` to upgrade to `20.04`
  - [ ] Test the deployed app w/ updated OS

**Comment by merlinoa** [comment]
I'm pretty sure this will work just fine now that Ubuntu packages have been updated.  No need to test ATM.
